sudo: required

language: node_js
node_js:
  - "8"

before_install:
  - 'curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0'
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

services:
  - docker
  - mongodb

jobs:
  include:
    - stage: test
      before_script:
        - sleep 15
        - mv .env .env.dev
        - mv .env.travis .env
      script:
        - yarn test
      cache:
        yarn: true
        directories:
          - node_modules

    - stage: test
      script:
        - yarn run format:ci
      cache:
        yarn: true
        directories:
          - node_modules

    - stage: build
      script:
        - docker login -u$QUAY_USER -p$QUAY_TOKEN quay.io/uzh-bf/klicker-api
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash -c "docker pull quay.io/uzh-bf/klicker-api:latest;docker build --cache-from quay.io/uzh-bf/klicker-api:latest -t quay.io/uzh-bf/klicker-api:latest .;docker push quay.io/uzh-bf/klicker-api:latest"; fi
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash -c "docker pull quay.io/uzh-bf/klicker-api:nightly;docker build --cache-from quay.io/uzh-bf/klicker-api:nightly -t quay.io/uzh-bf/klicker-api:nightly -t quay.io/uzh-bf/klicker-api:nightly-$TRAVIS_PULL_REQUEST .;docker push quay.io/uzh-bf/klicker-api:nightly; docker push quay.io/uzh-bf/klicker-api:nightly-$TRAVIS_PULL_REQUEST"; fi

