sudo: required

language: node_js
node_js:
  - "8"

branches:
  only:
    - master
    - /^greenkeeper/.*$/

services:
  - docker

jobs:
  include:
    - stage: test
      script:
        - yarn test
      cache:
        yarn: true
        directories:
          - node_modules

    - stage: build
      script:
        - docker login -u$QUAY_USER -p$QUAY_TOKEN quay.io/uzh-bf/klicker-api
        - docker pull quay.io/uzh-bf/klicker-api:latest
        - docker build --cache-from quay.io/uzh-bf/klicker-api:latest -t quay.io/uzh-bf/klicker-api:latest .
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash -c "docker push quay.io/uzh-bf/klicker-api:latest"; fi
