version: "3"

services:
  redis:
    # image: redis:5.0.9-32bit
    image: redis:3.2-32bit
    ports:
      - 6379:6379
    networks:
      - klicker-dev
    volumes:
      - /tmp/redis-data:/data
    # command: redis-server --appendonly yes

  mongodb:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: klicker
      MONGO_INITDB_ROOT_PASSWORD: klicker
    ports:
      - 27017:27017
    networks:
      - klicker-dev

networks:
  klicker-dev:
    driver: bridge
# minio:
#   image: minio/minio:latest@sha256:ed0c464a66ac1f56b77607320c74de4190cd6121b70ffbc1e387f2a4955dd334
#   volumes:
#     - minio-data:/data
#   ports:
#     - "9000:9000"
#   environment:
#     MINIO_ACCESS_KEY: klicker
#     MINIO_SECRET_KEY: secret123
#   command: server /data
# volumes: minio-data
