version: '3'
services:
  api:
    build: .
    ports:
      - "4000:3000"
    environment:
      APP_DOMAIN: "localhost"
      APP_SECRET: "hello-world"
      APP_FILTERING_FP:
      APP_FILTERING_IP:
      MONGO_URL: "klicker:klicker@ds125388.mlab.com:25388/klicker-migration"
      REDIS_URL: ":klicker-dev@144.76.118.118:6379"
      ORIGIN: "http://localhost:3000"
      PORT: 3000

  #redis:
    #image: "redis:3-32bit"
    #ports:
      #- "6379:6379"

  #mongodb:
    #image: "mongo:3.2"
    #ports:
      #- "27017:27017"
