version: '3'
services:
  api:
    build: .
    ports:
      - "4000:3000"
    environment:
      APP_DOMAIN: localhost
      APP_SECRET: hello-world
      MONGO_URL: mongodb/klicker

  mongodb:
    image: mongo:3.4.5
    ports:
      - "27017:27017"
