version: '3'
services:
  api:
    build: .
    ports:
      - "4000:3000"
    environment:
      APP_DOMAIN: localhost
      APP_SECRET: hello-world
      MONGO_URL: mongodb/klicker
      ORIGIN: http://localhost:3000
      PORT: 3000

  mongodb:
    image: mongo:3.2
    ports:
      - "27017:27017"
